[package]
name = "fdupe"
version = "0.1.0"
authors = ["Kristoffer Ödmark <kristoffer.odmark90@gmail.com>"]

[dependencies]
rayon = "*"
sha1 = "0.2.0"
[dev-dependencies]
file = "1.1.1"
tempdir = "0.3.5"
